repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python import sorter)
        language_version: python3.10

  - repo: https://github.com/psf/black
    rev: 23.7.0  # latest stable Black
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8 (python linter)
        additional_dependencies: [flake8-bugbear]
        language_version: python3.10
        max-line-length: 88
